"""Forensic lineage audit for local KwanTube files.

This script compares the current local repository tree against an optional
stable backup tree. It is intentionally read-only: it never modifies files and
never interacts with Git remotes.

Classification of delta entries (v3.5.1 semantics):
  SAME                   — file present in both trees with identical SHA-256.
  UPDATED                — file present in both trees but with different SHA-256
                           (legitimate code evolution since backup was taken).
  ADDED                  — file present only in current tree and not a relocation
                           (new module or new auxiliary tool).
  RELOCATED              — file absent from its old path but whose SHA-256 content
                           is present elsewhere in the current tree.
  DEPRECATED_INTENTIONAL — file absent from current tree, documented in the
                           v3.5.1 release notes as intentionally removed or
                           superseded. Does NOT trigger REVIEW_REQUIRED.
  REMOVED                — file truly absent from current tree with no SHA-256 match
                           and not in the known-evolution allowlist. Triggers review.

Generated files (*.pyc, __pycache__/) are always excluded: they are
auto-generated by the Python interpreter and carry no scientific content.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path


# ---------------------------------------------------------------------------
# SHA-256 utilities
# ---------------------------------------------------------------------------

def sha256(path: Path) -> str:
    """Compute SHA-256 digest for a file."""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1_048_576), b""):
            h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class FileLineage:
    """Comparison record for one relative path."""

    path: str
    current_exists: bool
    backup_exists: bool
    current_sha256: str | None
    backup_sha256: str | None
    status: str
    relocation_target: str | None = None


# ---------------------------------------------------------------------------
# Exclusion filter — auto-generated files carry no scientific content
# ---------------------------------------------------------------------------

_EXCLUDED_NAMES: frozenset[str] = frozenset({"__pycache__"})
_EXCLUDED_SUFFIXES: frozenset[str] = frozenset({".pyc", ".pyo"})


def _is_excluded(rel: Path) -> bool:
    """Return True for auto-generated files."""
    parts = rel.parts
    if any(p in _EXCLUDED_NAMES for p in parts):
        return True
    if rel.suffix in _EXCLUDED_SUFFIXES:
        return True
    return False


# ---------------------------------------------------------------------------
# v3.5.1 known-evolution allowlist
#
# Files that appear "missing" in the current tree relative to the
# KwanTube_repo_backup_estable_28042026 baseline are listed here with their
# disposition.  They are classified as DEPRECATED_INTENTIONAL rather than
# REMOVED and do NOT trigger REVIEW_REQUIRED in the verdict.
#
# Dispositions:
#   relocated+updated  — moved to a new path AND content was updated
#                        (SHA-256 change prevents automatic relocation detection)
#   outputs_relocated  — intermediate output files moved out of src/ into
#                        outputs_data/ (outside the default audit scope)
#   deprecated         — intentionally removed; functionality superseded
# ---------------------------------------------------------------------------

_V3_5_1_KNOWN_EVOLUTION: frozenset[str] = frozenset({
    # build_hamiltonian.py: moved from qmc_mt/ → scripts/analysis/ + updated
    "src/qmc_mt/build_hamiltonian.py",

    # heom_bayes_out_v2/: intermediate outputs relocated to outputs_data/
    "src/qmc_mt/heom_bayes_out_v2/diagnostics_v2.txt",
    "src/qmc_mt/heom_bayes_out_v2/extrapolated_jumps.csv",
    "src/qmc_mt/heom_bayes_out_v2/group_loglinear_summary.csv",
    "src/qmc_mt/heom_bayes_out_v2/hierarchy_global_contraction.csv",
    "src/qmc_mt/heom_bayes_out_v2/hierarchy_group_shrinkage.csv",
    "src/qmc_mt/heom_bayes_out_v2/level_reference_checks.csv",
    "src/qmc_mt/heom_bayes_out_v2/posterior_plots_v2.png",

    # heom_benchmark.py: deprecated; superseded by heom_production_driver.py
    "src/qmc_mt/heom_benchmark.py",

    # scripts_data_real/*: folder renamed → public_data/ + scripts updated
    "src/scripts/scripts_data_real/_audit_data.py",
    "src/scripts/scripts_data_real/build_registry.py",
    "src/scripts/scripts_data_real/compute_detectability_metrics.py",
    "src/scripts/scripts_data_real/curate_compact.py",
    "src/scripts/scripts_data_real/export_claim_traceability.py",
    "src/scripts/scripts_data_real/fetch_public_data.py",
    "src/scripts/scripts_data_real/run_comparative_panels.py",
    "src/scripts/scripts_data_real/run_pipeline_vscode.py",

    # Flat src/scripts/ top-level scripts: reorganised into subfolders + updated
    "src/scripts/bayesian_heom_hierarchy_v2.py",
    "src/scripts/extract_vector_figure.py",
    "src/scripts/generate_paper_figures.py",
    "src/scripts/reproduce_paper_results.py",
})


# ---------------------------------------------------------------------------
# Core comparison
# ---------------------------------------------------------------------------

def _collect_files(root: Path, bases: list[str]) -> dict[Path, str]:
    """Collect {relative_path: sha256} for all non-excluded files under base dirs."""
    result: dict[Path, str] = {}
    for base in bases:
        candidate = root / base
        if candidate.exists():
            for path in candidate.rglob("*"):
                if not path.is_file():
                    continue
                rel = path.relative_to(root)
                if _is_excluded(rel):
                    continue
                result[rel] = sha256(path)
    return result


def compare_trees(
    current_root: Path,
    backup_root: Path,
    bases: list[str],
) -> list[FileLineage]:
    """Compare current and backup trees under the given base directories."""

    current_files: dict[Path, str] = _collect_files(current_root, bases)
    backup_files:  dict[Path, str] = _collect_files(backup_root,  bases)

    # Reverse-index: sha256 → paths in current tree (enables relocation detection)
    current_sha_to_paths: dict[str, list[str]] = {}
    for rel, digest in current_files.items():
        current_sha_to_paths.setdefault(digest, []).append(
            str(rel).replace("\\", "/")
        )

    records: list[FileLineage] = []
    all_rels: set[Path] = set(current_files) | set(backup_files)

    for rel in sorted(all_rels):
        cur_sha = current_files.get(rel)
        bak_sha = backup_files.get(rel)
        rel_str = str(rel).replace("\\", "/")

        cur_exists = cur_sha is not None
        bak_exists = bak_sha is not None

        if cur_exists and bak_exists:
            status = "SAME" if cur_sha == bak_sha else "UPDATED"
            target = None

        elif cur_exists and not bak_exists:
            status = "ADDED"
            target = None

        elif bak_exists and not cur_exists:
            # Check: same content at a different path in current tree?
            other_paths = [
                p for p in current_sha_to_paths.get(bak_sha, [])
                if p != rel_str
            ]
            if other_paths:
                status = "RELOCATED"
                target = other_paths[0]
            elif rel_str in _V3_5_1_KNOWN_EVOLUTION:
                # Documented v3.5.1 evolution — not an unexpected deletion
                status = "DEPRECATED_INTENTIONAL"
                target = None
            else:
                # Genuinely missing with no explanation → needs manual review
                status = "REMOVED"
                target = None

        else:
            status = "ABSENT"
            target = None

        records.append(FileLineage(
            path=rel_str,
            current_exists=cur_exists,
            backup_exists=bak_exists,
            current_sha256=cur_sha,
            backup_sha256=bak_sha,
            status=status,
            relocation_target=target,
        ))

    return records


# ---------------------------------------------------------------------------
# Output formatting
# ---------------------------------------------------------------------------

_SEPARATOR = "─" * 62


def _build_verdict(counts: dict[str, int]) -> str:
    """Derive a one-line verdict from status counts.

    VERDICT: CLEAN  — no unexplained removals (REMOVED == 0).
    VERDICT: REVIEW_REQUIRED — at least one REMOVED file has no SHA-256 match
             and is not in the known-evolution allowlist.
    """
    removed    = counts.get("REMOVED", 0)
    updated    = counts.get("UPDATED", 0)
    added      = counts.get("ADDED", 0)
    reloc      = counts.get("RELOCATED", 0)
    deprecated = counts.get("DEPRECATED_INTENTIONAL", 0)
    same       = counts.get("SAME", 0)

    if removed == 0 and updated == 0 and added == 0 and reloc == 0 and deprecated == 0:
        return "IDENTICAL — current tree matches baseline exactly."

    if removed == 0:
        parts = []
        if same:       parts.append(f"{same} identical")
        if updated:    parts.append(f"{updated} updated (v3.5.1 evolution)")
        if added:      parts.append(f"{added} added")
        if reloc:      parts.append(f"{reloc} relocated")
        if deprecated: parts.append(f"{deprecated} deprecated/reorganised (documented)")
        return "CLEAN — " + "; ".join(parts) + ". No unexpected deletions."

    return (
        f"REVIEW_REQUIRED — {removed} file(s) absent from current tree without "
        f"SHA-256 match and not in known-evolution allowlist. "
        f"Manual verification required."
    )


def _print_summary(records: list[FileLineage], backup_path: Path, out_json: Path) -> None:
    """Print a clean, categorised summary to stdout."""

    counts: dict[str, int] = {}
    for r in records:
        counts[r.status] = counts.get(r.status, 0) + 1

    print(f"[audit_lineage] Baseline : {backup_path.name}")
    print(f"[audit_lineage] Compared (excl. __pycache__): {len(records)} files")
    print(f"[audit_lineage] {_SEPARATOR}")

    order = ["SAME", "UPDATED", "RELOCATED", "ADDED", "DEPRECATED_INTENTIONAL", "REMOVED"]
    labels = {
        "SAME":                  "SAME                    (identical to baseline)",
        "UPDATED":               "UPDATED                 (v3.5.1 legitimate evolution)",
        "RELOCATED":             "RELOCATED               (same content, reorganised path)",
        "ADDED":                 "ADDED                   (new modules / tooling)",
        "DEPRECATED_INTENTIONAL":"DEPRECATED_INTENTIONAL  (documented in v3.5.1 release)",
        "REMOVED":               "REMOVED ✗               (no SHA-256 match — verify)",
    }
    for status in order:
        n = counts.get(status, 0)
        if n > 0:
            print(f"[audit_lineage]   {labels[status]:56s}: {n:3d}")

    verdict = _build_verdict(counts)
    print(f"[audit_lineage] {_SEPARATOR}")
    print(f"[audit_lineage] VERDICT  : {verdict}")
    print(f"[audit_lineage] {_SEPARATOR}")

    # Only list truly unexpected removals (not deprecated ones)
    truly_removed = [r for r in records if r.status == "REMOVED"]
    if truly_removed:
        print("[audit_lineage] Files requiring manual review:")
        for r in truly_removed:
            print(f"[audit_lineage]   ✗ {r.path}")

    print(f"[audit_lineage] wrote {out_json}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    """Run a read-only lineage comparison and emit JSON report."""

    script_root    = Path(__file__).resolve().parents[3]   # KwanTube/
    workspace_root = script_root.parent

    parser = argparse.ArgumentParser(
        description="Audit current repo against stable backup (read-only)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--current", type=Path, default=script_root,
        help="Root of the current repository.",
    )
    parser.add_argument(
        "--backup", type=Path,
        default=workspace_root / "KwanTube_repo_backup_estable_28042026",
        help="Root of the stable baseline directory.",
    )
    parser.add_argument(
        "--out-json", type=Path,
        default=script_root / "outputs_data" / "raw_json" / "audit" / "lineage_audit.json",
        help="Destination for the JSON audit ledger.",
    )
    parser.add_argument(
        "--paths", nargs="*", default=["src/qmc_mt", "src/scripts"],
        help="Subdirectory paths to audit (relative to both roots).",
    )
    args = parser.parse_args()

    if not args.backup.exists():
        print(
            f"[audit_lineage] WARNING: backup directory not found: {args.backup}\n"
            f"[audit_lineage] Single-tree mode (all files classified as ADDED).",
            file=sys.stderr,
        )

    records = compare_trees(args.current, args.backup, args.paths)

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps([asdict(r) for r in records], indent=2), encoding="utf-8"
    )

    _print_summary(records, args.backup, args.out_json)
    return 0


if __name__ == "__main__":
    from pathlib import Path as _RunAuditPath
    import sys as _run_audit_sys
    for _run_audit_parent in _RunAuditPath(__file__).resolve().parents:
        if (_run_audit_parent / "qmc_mt" / "run_audit.py").exists():
            _run_audit_sys.path.insert(0, str(_run_audit_parent))
            break
    from qmc_mt.run_audit import install_run_audit as _install_run_audit
    _install_run_audit(__file__)
    raise SystemExit(main())