
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qmc_mt"
version = "3.5.1.1"
description = "KwanTube: reproducible open-system and convergence-validation framework for tubulin quantum dynamics"
authors = [
  { name = "Facundo Firmenich", email = "f.firmenich@cedesur.org" },
  { name = "Pau Firmenich" },
  { name = "León Firmenich" }
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib"
]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
